// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/tvseries/presentation/page/tvseries_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/Tvseries.dart' as _i10;
import 'package:ditonton/domain/entities/Tvseries_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/tvseries/get_tvseries_detail.dart'
    as _i2;
import 'package:ditonton/domain/usecases/tvseries/get_tvseries_recommendation.dart'
    as _i3;
import 'package:ditonton/domain/usecases/tvseries/get_tvseries_watchlist_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/tvseries/remove_tvseries_watchlist.dart'
    as _i6;
import 'package:ditonton/domain/usecases/tvseries/save_tvseries_watchlist.dart'
    as _i5;
import 'package:ditonton/presentation/provider/tvseries/tvseries_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvseriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTvseriesDetail {
  _FakeGetTvseriesDetail_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetSeriesRecommendation_1 extends _i1.SmartFake
    implements _i3.GetSeriesRecommendation {
  _FakeGetSeriesRecommendation_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetSeriesWatchListStatus_2 extends _i1.SmartFake
    implements _i4.GetSeriesWatchListStatus {
  _FakeGetSeriesWatchListStatus_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSaveSeriesWatchlist_3 extends _i1.SmartFake
    implements _i5.SaveSeriesWatchlist {
  _FakeSaveSeriesWatchlist_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRemoveSeriesWatchlist_4 extends _i1.SmartFake
    implements _i6.RemoveSeriesWatchlist {
  _FakeRemoveSeriesWatchlist_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvseriesDetail_5 extends _i1.SmartFake
    implements _i7.TvseriesDetail {
  _FakeTvseriesDetail_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TvseriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesDetailNotifier extends _i1.Mock
    implements _i8.TvseriesDetailNotifier {
  MockTvseriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvseriesDetail get getTvseriesDetail =>
      (super.noSuchMethod(Invocation.getter(#getTvseriesDetail),
              returnValue: _FakeGetTvseriesDetail_0(
                  this, Invocation.getter(#getTvseriesDetail)))
          as _i2.GetTvseriesDetail);
  @override
  _i3.GetSeriesRecommendation get getSeriesRecommendation =>
      (super.noSuchMethod(Invocation.getter(#getSeriesRecommendation),
              returnValue: _FakeGetSeriesRecommendation_1(
                  this, Invocation.getter(#getSeriesRecommendation)))
          as _i3.GetSeriesRecommendation);
  @override
  _i4.GetSeriesWatchListStatus get getSeriesWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getSeriesWatchListStatus),
              returnValue: _FakeGetSeriesWatchListStatus_2(
                  this, Invocation.getter(#getSeriesWatchListStatus)))
          as _i4.GetSeriesWatchListStatus);
  @override
  _i5.SaveSeriesWatchlist get saveSeriesWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveSeriesWatchlist),
              returnValue: _FakeSaveSeriesWatchlist_3(
                  this, Invocation.getter(#saveSeriesWatchlist)))
          as _i5.SaveSeriesWatchlist);
  @override
  _i6.RemoveSeriesWatchlist get removeSeriesWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeSeriesWatchlist),
              returnValue: _FakeRemoveSeriesWatchlist_4(
                  this, Invocation.getter(#removeSeriesWatchlist)))
          as _i6.RemoveSeriesWatchlist);
  @override
  _i7.TvseriesDetail get series => (super.noSuchMethod(
          Invocation.getter(#series),
          returnValue: _FakeTvseriesDetail_5(this, Invocation.getter(#series)))
      as _i7.TvseriesDetail);
  @override
  _i9.RequestState get seriesState =>
      (super.noSuchMethod(Invocation.getter(#seriesState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  List<_i10.Tvseries> get seriesRecommendation =>
      (super.noSuchMethod(Invocation.getter(#seriesRecommendation),
          returnValue: <_i10.Tvseries>[]) as List<_i10.Tvseries>);
  @override
  _i9.RequestState get seriesRecommendationState =>
      (super.noSuchMethod(Invocation.getter(#seriesRecommendationState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  String get seriesWatchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#seriesWatchlistMessage),
          returnValue: '') as String);
  @override
  bool get isAddedtoSeriesWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedtoSeriesWatchlist),
          returnValue: false) as bool);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchTvseriesDetail(int? idSeries) =>
      (super.noSuchMethod(Invocation.method(#fetchTvseriesDetail, [idSeries]),
              returnValue: _i11.Future<void>.value(),
              returnValueForMissingStub: _i11.Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> addSeriesWatchlist(_i7.TvseriesDetail? seriesDetail) =>
      (super.noSuchMethod(
              Invocation.method(#addSeriesWatchlist, [seriesDetail]),
              returnValue: _i11.Future<void>.value(),
              returnValueForMissingStub: _i11.Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromSeriesWatchlist(
          _i7.TvseriesDetail? seriesDetail) =>
      (super.noSuchMethod(
              Invocation.method(#removeFromSeriesWatchlist, [seriesDetail]),
              returnValue: _i11.Future<void>.value(),
              returnValueForMissingStub: _i11.Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> loadSeriesWatchlistStatus(int? idSeries) => (super
      .noSuchMethod(Invocation.method(#loadSeriesWatchlistStatus, [idSeries]),
          returnValue: _i11.Future<void>.value(),
          returnValueForMissingStub: _i11.Future<void>.value()) as _i11
      .Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
